# This is the Jupyter notebook template for Assignment 3

First, we load the needed modules (feel free to add more as needed)

In [1]:
%matplotlib inline
# Allows viewing figures inline in the notebook
import numpy as np
# Numpy is a library for numerical computation
import matplotlib.pyplot as plt
# Matplotlib is a plotting library

### Template for Exercise 4: Gradient descent for the Netflix Problem
Below, you will first load and view the data, and then fill in:
* The template function **netflix_gradient**, which computes the gradient of E with respect to a and b
* The gradient descent template function **netflix**, where you only need to fill in:
    * the update step (initialization and convergence criteria are already taken care of)
    * the computation of the gradient magnitude
    * you may also want to play with the learning rate
* Note: You may want to implement additional functions for debugging purposes

Start out by loading and viewing the data

In [2]:
# Load and view the incomplete matrix
M = np.loadtxt('data/netflix_matrix.txt')
# Uncomment if you want to view it
#print(M)

In [3]:
def netflix_gradient(M, A, B):
    # This function is meant to compute the gradient of E with respect to A and B
    # Given: * the (6 x 10) numpy array M, whose 0 inputs you want to replace by predictions, 
    #          and whose nonzero inputs you want to preserve
    #        * two variable numpy arrays A (of size 6 x 2) and B (of size 2 x 10), 
    #          over which you want to optimize to reconstruct the matrix M as well as possible as a product A*B.
    # Return: The gradients grad_A and grad_B of the cost function E from the exercise, 
    #         with respect to a and b, respectively. They should have the same shape as a and b.
    I = M.copy()

    for i in range(6) :
        for j in range(10) : 
            if M[i][j]!= 0 :
                I[i][j]=1
    
    grad_A = np.array([[0.0 for _ in range (2)] for _ in range(6)])
    grad_B = np.array([[0.0 for _ in range (10)] for _ in range(2)])
    
    for j in range(10) :
        for i in range (6) :
            for m in range(2) :
                grad_A[i][m] += ( 2*(I[i][j] * (-M[i][j]*B[m][j] + A[i][0]*B[0][j]*B[m][j] + A[i][1]*B[1][j]*B[m][j])))
    
    
    
    for i in range(6) :
        for m in range(2) :
            for j in range(10) :
                grad_B[m][j] += ( 2*(I[i][j] * (-M[i][j]*A[i][m] + (A[i][0]*A[i][m]*B[0][j]  + A[i][1]*A[i][m]*B[1][j]))) )
    
    return grad_A, grad_B

In [4]:
people,movies = M.shape
A = np.random.randn(people,2)
B = np.random.randn(2,movies)
M = np.loadtxt('data/netflix_matrix.txt')

netflix_gradient(M, A, B)

(array([[  6.58214476,   7.05470948],
        [ 51.41011298,  10.86608718],
        [ 18.47536829,   2.11554703],
        [ 40.70997782, -37.8844176 ],
        [-11.52492287,  -0.16289661],
        [  1.5719143 , -56.57883361]]),
 array([[-40.00786889, -31.4931686 ,  -9.62996094,   5.57404517,
          -3.76316248, -35.74130616, -57.84776049, -40.8446648 ,
          15.15112134, -30.63325691],
        [-20.36778163, -23.60052669, -52.47919776, -23.0275985 ,
         -16.56895741,  -5.94704374, -33.9555731 ,  -7.39991805,
         -10.48685027, -26.68399881]]))

In [5]:
def netflix(M):
    # A template function for performing gradient descent over A and B to minimize E
    # Input: The matrix M to be approximated
    people,movies = M.shape
    
    # Initialize at random
    np.random.seed(1) # Fixed seed for reproducibility; please don't change
    A = np.random.randn(people,2)
    B = np.random.randn(2,movies)
    
    # Set learning rate (you may want to play with this)
    learningrate = 0.00001
    
    # Setting parameters for convergence check
    num_iter = 1                   # This is the variable that will keep track of the number of iterations
    convergence = 0                # This is the variable that will keep track of whether we have converged
    max_iter = 100000               # We stop the algorithm after this many iterations
    tolerance = 0.01               # We conclude convergence when the magnitude of the gradient
                                   # is less than the tolerance
    
    while convergence == 0:
        ####################### MISSING PART ############## 
        # Compute gradient and take a step in the direction it dictates
        grad_A, grad_B = netflix_gradient(M, A, B)
        
        A = A - np.dot(grad_A, learningrate)
        B = B - np.dot(grad_B, learningrate)
        
        ####################### MISSING PART ##############        
        # Check for convergence -- you need to fill in the computation of the norm of the gradient at the current location
        num_iter = num_iter + 1      
        cur_grad_norm = np.sqrt(np.linalg.norm(grad_A)**2 + np.linalg.norm(grad_B)**2)
        
        if cur_grad_norm < tolerance:
            convergence = 1
            print('converged')
        elif num_iter > max_iter:
            convergence = 1 
            print('reached maximum nr of iterations')
    return A, B

Next, run your code to return your resulting A, B and A*B, and compare it with M

In [6]:

M = np.loadtxt('data/netflix_matrix.txt')

A, B = netflix(M)

M_pred = np.matmul(A,B)


for i in range(6) :
    for j in range(10):
        M_pred[i][j] = round(M_pred[i][j])

M_fill = M.copy()

for i in range(6) :
    for j in range(10):
        if M_fill[i][j] ==0 :
            M_fill[i][j]= M_pred[i][j]

print ("ORIGINAL M : \n", M)
print ("PREDiCTED M : \n", M_pred)



print ("M FILLED HOLES : \n", M_fill)


reached maximum nr of iterations
ORIGINAL M : 
 [[ 7.  8.  9.  0.  0.  1.  4.  2.  3.  9.]
 [ 0.  0. 10.  9. 10.  2.  3.  0.  0.  5.]
 [10.  9.  0.  8.  0.  0.  0.  2.  1.  3.]
 [ 1.  0.  2.  0.  0.  9.  8.  9.  0.  0.]
 [ 0.  1.  1.  0.  2.  0.  9.  0.  7.  0.]
 [ 2.  1.  0.  0.  1. 10.  0.  9.  0.  8.]]
PREDiCTED M : 
 [[ 8.  8. 10. 10. 10.  2.  4.  4.  3.  6.]
 [ 8.  8. 10.  9. 10.  1.  3.  3.  3.  6.]
 [ 9.  9. 11.  8. 12. -2.  1.  1.  1.  4.]
 [ 2.  1.  2.  9.  2.  9.  8.  9.  6.  9.]
 [ 1.  1.  1. 10.  2. 11.  9. 10.  7. 10.]
 [ 1.  1.  1.  9.  1. 10.  8.  9.  6.  9.]]
M FILLED HOLES : 
 [[ 7.  8.  9. 10. 10.  1.  4.  2.  3.  9.]
 [ 8.  8. 10.  9. 10.  2.  3.  3.  3.  5.]
 [10.  9. 11.  8. 12. -2.  1.  2.  1.  3.]
 [ 1.  1.  2.  9.  2.  9.  8.  9.  6.  9.]
 [ 1.  1.  1. 10.  2. 11.  9. 10.  7. 10.]
 [ 2.  1.  1.  9.  1. 10.  8.  9.  6.  8.]]
